### ISSUE TITLE
Rasters with time series data don't keep their "time" location when turned on/off, nor when creating direct link

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#15]
I'll try to explain the problem the best I can:
1- when there is a layer turned on with time series data, the time slider below can change the date being shown. However, if the layer is switched off, and then on again, there is no "memory" of what date it was being shown and it goes back to default (last avail).
2- similar with several time-series layers on display, it would be good if all layers change date (or to the closest available date) together. 

example with 3 layers on display:
http://map.geo-rapp.org/#share=s-flgmn8mCgPVEGv6AQ9krbodPf7f

**Comment by meh9** [comment]
This is being worked on in: https://github.com/TerriaJS/terriajs/pull/2572

**Comment by a-stacey** [comment]
Just checking that you linked the right code there @meh9 because my understanding is that these two requests (listed in the description) are for different features then the one addressed in TerriaJS/terriajs#2572. The issue listed in TerriaJS/terriajs#2572 does address the second part of the issue title "Rasters with time series data don't keep their "time" location ... when creating direct link"

**Comment by meh9** [comment]
@a-stacey, yes, you are correct, I misunderstood, this is something different and not exactly what I linked to.

**Comment by tephenavies** [comment]
I had a bit of a poke around CatalogItem, ImageryLayerCatalogItem and WebMapServiceCatalogItem and it looks like the problem could be a one way sync between Cesium `DataSourceClock`s and counting time by incrementing the `_currentIntervalIndex` property. 

Animating a layer changes it's `_currentIntervalIndex`. Hiding the layer preserves that until you unhide the layer, when Cesium's clock is updated from the catalog item's clock and then `_currentIntervalIndex` is set from there. But since the item's clock is never changed while animating, it's time lines up with the last time interval.

Does that sound right @kring?

**Comment by kring** [comment]
Sounds right to me.

**Comment by meh9** [comment]
I believe this is now fixed.
