### ISSUE TITLE
Make Query Data more visible

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#21]
Currently Query Data is within Data Catalogue and not obvious for many users. 
Is it possible to make it more visible? 
Option 1: 
Next to the Add data button (e.g. split that space in two)

Option 2: Next to My Data as a third button. 

see img below. 

![media-20170704](https://user-images.githubusercontent.com/8801702/27811149-27cf34a8-60a6-11e7-9b3f-9225e0103247.png)

**Comment by mpaget** [comment]
Alternatively, consider:
1) 'Analysis tools' category to help draw the eye to the bold category label.
2) Each *.ini file creates a separate tab in the Add data window (Mats' idea)

**Comment by a-stacey** [comment]
After discussion with @meh9 and @kring yesterday we have decided that we will add a tool element to make it more visible.

E.g.
![analysis](https://user-images.githubusercontent.com/4453477/29543180-9ef1f24e-8722-11e7-9c15-2eeb6aed108c.png)

This will be implemented generically so that it makes it easier to add further elements in the future.

After discussing the above with @juan-guerschman will look at splitting the current single analysis into 3 queries and grouping them into a category and the tool element will link to one of the queries in the category.

**Comment by juan-guerschman** [comment]
hey, back to this ticket. Now with tabs this would be quite straightforward: 
Just a new tab for Analysis tools with three options inside. 
I guess @meh9 already working on it but I bring it up here anyway. 

![image](https://user-images.githubusercontent.com/8801702/33407225-7242d326-d5c4-11e7-9eb0-7ef417f6e931.png)

**Comment by a-stacey** [comment]
My understanding is that this has been completed now but I will leave this to @meh9 or @juan-guerschman to confirm or close (just going through some old issues assigned to me and trying to clean them up).

**Comment by juan-guerschman** [comment]
yes, with tabs we solved most of the problem.
