### ISSUE TITLE
Increase the size limit for uploaded shapefiles, currently 1MB

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#37]
A user wants to upload shapefiles of sizer larger than 1MB. Not sure what's a practical limit, but if possible 10 or 20 MB would be much better.

**Comment by a-stacey** [comment]
Have updated the limit so that it is now set to 20MB (have not validated the performance of this on a remote connection so we will just have to see if this creates an issues for people uploading larger files - but locally this seems to work fine).

Have submitted a PR to TerriaJS so that the client-side validation will now use the server validation value. But we will need to wait till this PR is merged and geoglam is updated to use the merged version before this will have effect.

**Comment by juan-guerschman** [comment]
great, thanks @a-stacey . Can you let me know when this takes effect so I test it?

**Comment by a-stacey** [comment]
This is in production and have tested with the Australian Rangelands 7MB sample file that we have. The limit should now be 20MB.
